### ISSUE TITLE
Can't run ITER2D notebook

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [gabriele-ferrero/Titans_TT_codecomparison#10]
I'm trying to run the ITER2D notebook in `Festim models/Jupyter_notebooks` and I can't run it because it doesn't find the `materials` module.

I notice a lot of code duplication between jupyter notebooks and python scripts. Maybe you can either get rid of the notebooks, or have the notebooks import the python scripts.

**Comment by gabriele-ferrero** [comment]
Notebook were implemented for easyness of use and then have been moved in another folder. I'll check the dependencies and make it work as I have enough time also to test it.  
Working code >> easy to use code

**Comment by RemDelaporteMathurin** [comment]
Maybe the notebooks are not needed at all since it's just duplicated code (or an attempt at... see #15 )

Notebooks can also import python scripts which would get rid of this issue
