### ISSUE TITLE
No need to redefine `DissociationFlux`

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [gabriele-ferrero/Titans_TT_codecomparison#12]
The dissociation flux is[ implemented in FESTIM 1.1.1](https://github.com/festim-dev/FESTIM/blob/v1.1.1/festim/boundary_conditions/fluxes/dissociation_flux.py) there is no need to redefine it in TDS_EUROFER_festim.py

**Comment by gabriele-ferrero** [comment]
Probably it was not implemented or I needed to tailor it (at first) when I first did the research, I'll delete it and test it soon
