### ISSUE TITLE
Error in mathtex in matplotlib

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [gabriele-ferrero/Titans_TT_codecomparison#9]
I found another error in the notebooks (before running into #8) in graph_scripts_and_results.

The line:

```
plt.ylabel(r'Flux $D_2 /(m^{2} s)}$', size=16)
```

Appears several times (in StrongTrap.ipynb and in StrongTrapPlot.ipynb for instance). There are extra `}` here which makes the code fail.

```
ValueError: 
Flux $D_2 /(m^{2} s)}$
     ^
ParseException: Expected end of text, found '$'  (at char 5), (line:1, col:6)
```

For example here:
https://github.com/gabriele-ferrero/Titans_TT_codecomparison/blob/ff5ee755b4d892a7961d197bb906b07aae63600c/graph_scripts_and_results/WeakTrap/PlotWeak.ipynb#L75

**Comment by gabriele-ferrero** [comment]
Typos, will fix soon
